# action.yml
name: 'Vulcan Auto Patch Generator'
description: 'Auto fix on the branch which triggers a workflow'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  path:
    description: 'Checkout directory name'
    default: 'target'
  
runs:
  using: 'composite'
  steps:
    - name: Set permissions as excutable
      run: chmod +x -R $GITHUB_ACTION_PATH/vulcan
      shell: bash
    - name: Checkout vulcan target
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        persist-credentials: false

    - name: Reconfigure git to use HTTP authentication
      shell: bash
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - run: $GITHUB_ACTION_PATH/vulcan/entry.sh
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        VULCAN_TARGET: ${{ inputs.path }}
